// Real customer/client/distributor names sourced from the Cospharm contact list
// (Filtered_Groups_Names_Telephone.xlsx). Do not invent additional names.

export type ClientType = "Distributor" | "Hospital" | "Pharmacy" | "Retail Chain" | "Other";

export interface ClientRecord {
  name: string;
  phone: string | null;
  type: ClientType;
}

export const PHARMA_DISTRIBUTORS_FULL: ClientRecord[] = [
  { name: "Poldero Bio Pharma", phone: "+267 39 605 71", type: "Distributor" },
  { name: "First Care Distributors", phone: null, type: "Distributor" },
  { name: "Orthosurge Pharmaceuticals", phone: null, type: "Distributor" },
  { name: "Infinity Group", phone: null, type: "Distributor" },
  { name: "Medical Logistics Solution", phone: null, type: "Distributor" },
  { name: "Choppies Enterprises Ltd", phone: null, type: "Distributor" },
  { name: "Bet - Elixir Pharmaceuticals", phone: "+267 68 010 19", type: "Distributor" },
  { name: "Logistics Solutions", phone: null, type: "Distributor" },
  { name: "Green Plus Pharma", phone: "+267 3922702", type: "Distributor" },
  { name: "Alpha Pharmaceuticals", phone: "+267 24 110 22", type: "Distributor" },
  { name: "Lorah Distributors Pty Ltd", phone: "+267 31 910 35", type: "Distributor" },
  { name: "Premier Pharma Trade", phone: "+267 39 006 06", type: "Distributor" },
  { name: "Mediland Healthcare Distributors", phone: "+267 39 027 86", type: "Distributor" },
  { name: "Medic Plus Pharmaceutical", phone: null, type: "Distributor" },
  { name: "Kalahari Medical Distributors", phone: "+267 3934750", type: "Distributor" },
  { name: "International Pharmaceutical Alliance", phone: null, type: "Distributor" },
  { name: "Grand Pharma Distributors (Pty) Ltd", phone: "+267 39 300 89", type: "Distributor" },
  { name: "Delta Pharmaceuticals", phone: null, type: "Distributor" },
  { name: "Botoka Pharmaceuticals", phone: "+267 39 535 83", type: "Distributor" },
];

export const HOSPITALS_AND_CLINICS_FULL: ClientRecord[] = [
  { name: "Haven City Medical Clinic", phone: null, type: "Hospital" },
  { name: "Medlane Day Hospital", phone: null, type: "Hospital" },
  { name: "Restore Family Clinic", phone: null, type: "Hospital" },
  { name: "Urban Medical Clinic", phone: null, type: "Hospital" },
  { name: "Medicare Medical", phone: null, type: "Hospital" },
  { name: "Eden Clinic", phone: null, type: "Hospital" },
  { name: "New Day Medical Center", phone: null, type: "Hospital" },
  { name: "Dr Miko Private Clinic", phone: "+267 72470208", type: "Hospital" },
  { name: "Palm Grove Medical Clinic", phone: "+267 35 007 67", type: "Hospital" },
  { name: "Myga Medical Center", phone: null, type: "Hospital" },
  { name: "Gaborone Fertility Clinic", phone: "+267 39 130 95", type: "Hospital" },
  { name: "Elonga Medical Clinic", phone: null, type: "Hospital" },
  { name: "Aarat Medical Center", phone: null, type: "Hospital" },
  { name: "Sarha Clinic", phone: null, type: "Hospital" },
  { name: "Mabutsane Private Clinic", phone: "+267 71401398", type: "Hospital" },
  { name: "Bethsaida Medical Center", phone: null, type: "Hospital" },
  { name: "Kumakwane Private Clinic", phone: null, type: "Hospital" },
  { name: "Express Care Private Clinic", phone: null, type: "Hospital" },
  { name: "Jordan River of Life Clinic", phone: null, type: "Hospital" },
  { name: "Multi Care Medical Center", phone: "+267 39 137 31", type: "Hospital" },
  { name: "Hill Top Medical Center", phone: "+267 74547178", type: "Hospital" },
  { name: "AO Clinic Maun", phone: "+267 77747292", type: "Hospital" },
  { name: "Kalafhi Day Hospital", phone: null, type: "Hospital" },
  { name: "Angel Private Clinic", phone: "+267 72309700", type: "Hospital" },
  { name: "Olive Medical Centre", phone: "+267 71966545(Mr Ramosamo", type: "Hospital" },
  { name: "Botho Medical Surgery", phone: null, type: "Hospital" },
  { name: "Bagaetsho Medical Centre", phone: "+267 58 870 90", type: "Hospital" },
  { name: "Espoir Clinic", phone: "+267 76091577", type: "Hospital" },
  { name: "Life Line Medical Clinic", phone: null, type: "Hospital" },
  { name: "Genomed Clinic", phone: "+267 24 101 39", type: "Hospital" },
  { name: "Botshelo Medical Centre", phone: null, type: "Hospital" },
  { name: "Clinica Fermina", phone: "+267 76 437 191", type: "Hospital" },
  { name: "Thusong Surgery", phone: null, type: "Hospital" },
  { name: "Phikwe Medical Centre", phone: "+267 26 005 44", type: "Hospital" },
  { name: "City Medical Centre", phone: "+267 2442042", type: "Hospital" },
  { name: "AO Clinic Tlokweng", phone: null, type: "Hospital" },
  { name: "Maisha Medical Centre", phone: "+267 65 402 44", type: "Hospital" },
  { name: "AO Clinic Kweneng", phone: null, type: "Hospital" },
  { name: "Satellite Private Medical Clinic", phone: "+267 24 063 52", type: "Hospital" },
  { name: "Kabala Medical Centre", phone: "+267 74868032", type: "Hospital" },
  { name: "The Mall Gynae Clinic", phone: "+267 39 100 76", type: "Hospital" },
  { name: "Fairground Medical Centre", phone: "+267 31 176 43", type: "Hospital" },
  { name: "Sarona Health Clinic", phone: "+267 39 243 07", type: "Hospital" },
  { name: "Gabriel Clinic", phone: "+267 74052072", type: "Hospital" },
  { name: "Hospital Way Medical Centre", phone: "+267 76665104", type: "Hospital" },
  { name: "Bookelo Medical Centre", phone: "+267 24 204 05", type: "Hospital" },
  { name: "Goodwill Medical centre", phone: "+267 74176819", type: "Hospital" },
  { name: "E& P Medical Centre", phone: "+267 39 110 24", type: "Hospital" },
  { name: "Tsogo Medical Centre", phone: "+267 39 274 44", type: "Hospital" },
  { name: "Tlokweng Medi- Clinic", phone: "+267 39 283 15", type: "Hospital" },
  { name: "Barakat Medical Centre", phone: "+267 39 600 07", type: "Hospital" },
  { name: "First Care Clinic", phone: "+267 393 0090", type: "Hospital" },
  { name: "Nata Medical Centre", phone: null, type: "Hospital" },
  { name: "Enele Medical Centre", phone: "+267 4720002", type: "Hospital" },
  { name: "Triple Kadosh Medical Centre", phone: "+267 39 350 30", type: "Hospital" },
  { name: "Sebele Centre Private Clinic", phone: "+267 39 017 74", type: "Hospital" },
  { name: "ST Damian Medical Clinic", phone: null, type: "Hospital" },
  { name: "Francistown Clinic", phone: "+267 24 184 58", type: "Hospital" },
  { name: "Maun Private Hospital", phone: "+267 68 602 45", type: "Hospital" },
  { name: "Mogoditshane Family Clinic", phone: "+267 39 093 15", type: "Hospital" },
  { name: "The Family Clinic & Surgery", phone: "+267 39 170 03", type: "Hospital" },
  { name: "Healthscope Medical Centre", phone: null, type: "Hospital" },
  { name: "Ndebora Medical Centre", phone: "+267 58 870 97", type: "Hospital" },
  { name: "Tutume Medical Centre", phone: null, type: "Hospital" },
  { name: "Pholoso Medical Centre Ramotswa", phone: null, type: "Hospital" },
  { name: "Aqua Spray Private Clinic", phone: "+267 24 083 80", type: "Hospital" },
  { name: "Hukuntsi Private Clinic", phone: "+267 65 101 01", type: "Hospital" },
  { name: "Phodisong Medical Clinic", phone: null, type: "Hospital" },
  { name: "Flower Town Medical Centre", phone: "+267 47 120 34", type: "Hospital" },
  { name: "St Josephs Clinic", phone: null, type: "Hospital" },
  { name: "Ditalala clinic", phone: null, type: "Hospital" },
  { name: "Kgatleng Medical Centre", phone: null, type: "Hospital" },
  { name: "Atlega Medical Centre", phone: null, type: "Hospital" },
  { name: "Tegra Medical Clinic", phone: null, type: "Hospital" },
  { name: "Chilani Clinic", phone: null, type: "Hospital" },
  { name: "The Choice Medical Centre", phone: "+267 39 355 74", type: "Hospital" },
  { name: "Thembo Yetu Clinic", phone: null, type: "Hospital" },
  { name: "Cedmol Medical Centre", phone: "+267 39 222 31", type: "Hospital" },
  { name: "Independence Surgery", phone: "+267 39 534 24", type: "Hospital" },
  { name: "Acacia  Medicare Clinic", phone: null, type: "Hospital" },
  { name: "Tumelo Medicare Centre", phone: "+267 49 200 92", type: "Hospital" },
  { name: "Lords Land Medical Centre", phone: "+267 24 196 96", type: "Hospital" },
  { name: "Ultra Care Clinic (Mochudi)", phone: "+267 73969144", type: "Hospital" },
  { name: "Tati Side Medical Centre", phone: "+267 71642090", type: "Hospital" },
  { name: "Botsogo Medical Centre", phone: "+267 57 294 13", type: "Hospital" },
  { name: "DR Mananga - Mogoditshane ABC clinic", phone: null, type: "Hospital" },
  { name: "St Francis Medical Clinic", phone: "+267 54 900 19", type: "Hospital" },
  { name: "DR Kabong Clinic", phone: null, type: "Hospital" },
  { name: "Liberty Medical Centre (Otse)", phone: null, type: "Hospital" },
  { name: "Medikon Clinic", phone: "+267 54 418 84", type: "Hospital" },
  { name: "Rossignol Private Clinic", phone: "+267 74919985", type: "Hospital" },
  { name: "Quality  Health Clinic", phone: "+267 39 351 75", type: "Hospital" },
  { name: "Winner Medical Centre (Moshupa)", phone: "+267 54 493 73", type: "Hospital" },
  { name: "Victorious living medical clinic", phone: "+267 76050249", type: "Hospital" },
  { name: "The Village Surgery", phone: null, type: "Hospital" },
  { name: "Sidilega Private Hospital", phone: null, type: "Hospital" },
  { name: "Shammah Medical Centre(Lentseletau)", phone: null, type: "Hospital" },
  { name: "Riverside Hospital", phone: "+267 24 283 12", type: "Hospital" },
  { name: "Star Polyhealth Clinic", phone: "+267 39 336 98", type: "Hospital" },
  { name: "Oristone Medical Clinic", phone: null, type: "Hospital" },
  { name: "Moshupa Private Clinic", phone: null, type: "Hospital" },
  { name: "Masedi Medical Clinic", phone: null, type: "Hospital" },
  { name: "Life Centre Clinic", phone: null, type: "Hospital" },
  { name: "Karong Clinics", phone: null, type: "Hospital" },
  { name: "Hamilton Medical Centre", phone: null, type: "Hospital" },
  { name: "Gaborone Private Hospital", phone: null, type: "Hospital" },
  { name: "Care & Hope Clinic", phone: "+267 59 999 87", type: "Hospital" },
  { name: "Bokamoso Private Hospital", phone: "+267 36 949 53", type: "Hospital" },
  { name: "Block 5 Private Clinic", phone: null, type: "Hospital" },
  { name: "Avenue Medical Centre", phone: null, type: "Hospital" },
  { name: "Acacia Clinic", phone: "+267 59 997 20", type: "Hospital" },
];

export const PHARMACIES_FULL: ClientRecord[] = [
  { name: "Zebra Pharmacy", phone: null, type: "Pharmacy" },
  { name: "Thusano Chemist", phone: null, type: "Pharmacy" },
  { name: "DR Lambat Dispensary", phone: "+267 39 532 33", type: "Pharmacy" },
];

export const RETAIL_CHAINS_FULL: ClientRecord[] = [
  { name: "On The Go - Choppies - Fairgrounds", phone: null, type: "Retail Chain" },
  { name: "Choppies Hyper - North Gate Mall", phone: "+267 31 872 67", type: "Retail Chain" },
  { name: "Choppies Superstore - Mogoditshane Centre", phone: null, type: "Retail Chain" },
  { name: "Choppies Hyper - Gamecity", phone: "+267 31 607 72", type: "Retail Chain" },
  { name: "Choppies Hyper - Station", phone: "+267 39 344 04", type: "Retail Chain" },
  { name: "Choppies Hyper -Westgate", phone: "+267 39 255 19", type: "Retail Chain" },
  { name: "On The Go - Molepolole", phone: null, type: "Retail Chain" },
  { name: "On The Go - Tonota", phone: null, type: "Retail Chain" },
  { name: "On The Go - Mochudi", phone: null, type: "Retail Chain" },
  { name: "On the Go - Morwa", phone: null, type: "Retail Chain" },
  { name: "On the Go - Gweta", phone: null, type: "Retail Chain" },
  { name: "On the Go - Choppies - Mahalapye", phone: null, type: "Retail Chain" },
  { name: "On the Go-Choppies - Boatle", phone: null, type: "Retail Chain" },
  { name: "Choppies Superstore Village Gatemall - Molepolole", phone: null, type: "Retail Chain" },
  { name: "Choppies Hyperstore - Francistown", phone: null, type: "Retail Chain" },
  { name: "Choppies Superstore Borakalalo - Molepolole", phone: "+267 59 200 59", type: "Retail Chain" },
  { name: "Choppies Superstore - Jwaneng", phone: null, type: "Retail Chain" },
  { name: "Choppies Super Store - Hill side", phone: null, type: "Retail Chain" },
];

export const OTHER_CUSTOMERS_FULL: ClientRecord[] = [
  { name: "Med Harbor", phone: "+267 39 608 16", type: "Other" },
  { name: "Monteco (Private market)", phone: null, type: "Other" },
  { name: "Oms Health Pty Ltd (Private market)", phone: null, type: "Other" },
  { name: "Tswana Pharm", phone: "+267 31 111 15", type: "Other" },
  { name: "Ginomoch Investments", phone: "+267 72753581", type: "Other" },
  { name: "Afriark Animal Health", phone: null, type: "Other" },
  { name: "The Medic Center", phone: null, type: "Other" },
  { name: "Elraphah Medical", phone: null, type: "Other" },
  { name: "Medlex Health Care Center", phone: null, type: "Other" },
  { name: "Village Oncology", phone: null, type: "Other" },
  { name: "Linkjar (Pty) Ltd", phone: null, type: "Other" },
  { name: "Health Harvest Investments Pty Ltd", phone: null, type: "Other" },
  { name: "Compass Green", phone: "+267 31 190 13", type: "Other" },
  { name: "Eternity Medical Practice", phone: "+267 39 700 09", type: "Other" },
  { name: "Vetswana Botswana", phone: "+267 53 061 66", type: "Other" },
  { name: "Phemo Wellness Centre", phone: "+267 31 911 81", type: "Other" },
  { name: "Doctor's Inn (Pty) Ltd", phone: "+267 68 651 15", type: "Other" },
  { name: "Oxbow Investments (PTY) Ltd", phone: null, type: "Other" },
  { name: "Spectra Health Solutions", phone: "+267 31 173 84", type: "Other" },
  { name: "Poly Health Services", phone: "+267 39 514 33", type: "Other" },
  { name: "DR Mwaipopo", phone: null, type: "Other" },
  { name: "Cash Customer", phone: null, type: "Other" },
  { name: "DR Erasmus (Phakalane )", phone: "+267 71575257", type: "Other" },
  { name: "SK Medlinks", phone: null, type: "Other" },
  { name: "Medswana Pty Ltd", phone: "+267 39 599 30", type: "Other" },
  { name: "Ledertech Medical Supplies", phone: null, type: "Other" },
  { name: "KT Healthcare pty ltd", phone: null, type: "Other" },
  { name: "Kiran Medical C entre", phone: null, type: "Other" },
  { name: "Kalafi-Village", phone: null, type: "Other" },
  { name: "Gaborone Cancer Centre", phone: "+267 31 105 64", type: "Other" },
  { name: "Fine Phamaceuticals Pty Ltd", phone: null, type: "Other" },
  { name: "Desert Doctor Pty Ltd", phone: null, type: "Other" },
  { name: "David Phamarceuticals", phone: "+267 39 368 93", type: "Other" },
  { name: "Medical Devices Botswana", phone: null, type: "Other" },
];

export const ALL_CLIENT_RECORDS: ClientRecord[] = [
  ...PHARMA_DISTRIBUTORS_FULL,
  ...HOSPITALS_AND_CLINICS_FULL,
  ...PHARMACIES_FULL,
  ...RETAIL_CHAINS_FULL,
  ...OTHER_CUSTOMERS_FULL,
];

// Back-compat exports used by older components.
export const PHARMA_DISTRIBUTORS = PHARMA_DISTRIBUTORS_FULL.map((c) => c.name);
export const HOSPITALS_AND_CLINICS = HOSPITALS_AND_CLINICS_FULL.map((c) => c.name);
export const ALL_CLIENTS = ALL_CLIENT_RECORDS.map((c) => c.name);
export const CLIENT_CONTACTS: Record<string, string> = Object.fromEntries(
  ALL_CLIENT_RECORDS.filter((c) => c.phone).map((c) => [c.name, c.phone as string]),
);
